global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "micro-consent-pipeline-api"
    static_configs:
      - targets: ["micro-consent-pipeline:8000"]
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: "micro-consent-pipeline-streamlit"
    static_configs:
      - targets: ["micro-consent-pipeline:8501"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
